import Navbar from "./components/layout-three/Navbar";
import Footer from "./components/ui/Footer";
import "./globals.css";


export const metadata = {
  title: "Landing Page Two",
  description: "Generated by Landing Page",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar isWhiteBg={true} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
